apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - image: srinivasarao2468/assignment:v1
        name: assignment
        ports:
        - containerPort: 8080
